version: "3"
services:
  zookeeper:
    container_name: 'zookeeper'
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app
    profiles:
      - infra
      - bpi
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - app
    depends_on:
      - zookeeper
    profiles:
      - infra
      - bpi
  ganache-cli:
    image: 'trufflesuite/ganache-cli:latest'
    container_name: 'ganache-cli'
    ports:
      - '8545:8545'
    networks:
      - p1
      - p2
    profiles:
      - infra
      - bpi
  p1-bpi:
    build:
      context: ../server
      dockerfile: ../server/Dockerfile
    container_name: 'p1-bpi'
    ports:
      - '3001:3000'
    networks:
       - p1
       - app
    environment:
      - PROOF_SERVICE=p1-proof:3000
      - KAFKA_GROUP='p1-kafka'
      - KAFKA_BROKER=kafka:9092
      - PLAYER_ID=P1
    depends_on:
      - p1-proof
      - ganache-cli
    profiles:
      - bpi
  p2-bpi:
    build:
      context: ../server
      dockerfile: ../server/Dockerfile
    container_name: 'p2-bpi'
    ports:
      - '3003:3000'
    networks:
      - p2
      - app
    environment:
      - PROOF_SERVICE=p2-proof:3000
      - KAFKA_GROUP='p2-kafka'
      - KAFKA_BROKER=kafka:9092
      - PLAYER_ID=P2
    depends_on:
      - p2-proof
      - ganache-cli
    profiles:
      - bpi
  p1-proof:
    build:
      context: ../server/baseline/privacy/gnark
    container_name: 'p1-proof'
    ports:
      - '3002:3000'
    networks:
      - p1
    profiles:
      - bpi
  p2-proof:
    build:
      context: ../server/baseline/privacy/gnark
    container_name: 'p2-proof'
    ports:
       - '3004:3000'
    networks:
       - p2
    profiles:
      - bpi
networks:
  app:
    driver: bridge
  p1:
    driver: bridge
  p2:
    driver: bridge